simplification

diff --git a/etc/init.d/mongod b/etc/init.d/mongod
--- a/etc/init.d/mongod
+++ b/etc/init.d/mongod
@@ -12,48 +12,39 @@
 # Description:    Mongod
 ### END INIT INFO
 
-# Source function library.
-. /etc/rc.status
-rc_reset
-
 # things from mongod.conf get there by mongod reading it
 
+EZPAARSE_MONGO_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../.." && pwd )"
 
 # NOTE: if you change any OPTIONS here, you get what you pay for:
 # this script assumes all options are in the config file.
-CONFIGFILE="{{ezpaarse-mongo-path}}/etc/mongod.conf"
+CONFIGFILE="${EZPAARSE_MONGO_PATH}/etc/mongod.conf"
+PIDFILEPATH="${EZPAARSE_MONGO_PATH}/var/run/mongod.pid"
+
 OPTIONS=" -f $CONFIGFILE"
 SYSCONFIG="/etc/sysconfig/mongod"
 
-DBPATH=`awk -F= '/^dbpath[[:blank:]]*=[[:blank:]]*/{print $2}' "$CONFIGFILE"`
-PIDFILEPATH=`awk -F= '/^pidfilepath[[:blank:]]*=[[:blank:]]*/{print $2}' "$CONFIGFILE"`
+PIDDIR=`dirname "${PIDFILEPATH}"`
 mongod=${MONGOD-/usr/bin/mongod}
-
-MONGO_USER={{ezpaarse-mongo-user}}
-MONGO_GROUP={{ezpaarse-mongo-group}}
 
 if [ -f "$SYSCONFIG" ]; then
     . "$SYSCONFIG"
 fi
 
-# Handle NUMA access to CPUs (SERVER-3574)
-# This verifies the existence of numactl as well as testing that the command works
-NUMACTL_ARGS="--interleave=all"
-if which numactl >/dev/null 2>/dev/null && numactl $NUMACTL_ARGS ls / >/dev/null 2>/dev/null
-then
-    NUMACTL="$(which numactl) $NUMACTL_ARGS"
-else
-    NUMACTL=""
-fi
 
 start()
 {
 
   # Make sure the default pidfile directory exists
-  if [ ! -d $PIDDIR ]; then
-    install -d -m 0755 -o $MONGO_USER -g $MONGO_GROUP $PIDDIR
+  if [ ! -d ${PIDDIR} ]; then
+    mkdir -p ${PIDDIR}
   fi
 
+  if [ ! -f ${CONFIGFILE} ]; then
+    echo "${CONFIGFILE} not found"
+    echo "You should run init-config first"
+    exit 1; 
+  fi
   # Recommended ulimit values for mongod or mongos
   # See http://docs.mongodb.org/manual/reference/ulimit/#recommended-settings
   #
@@ -65,20 +56,20 @@ start()
   #ulimit -u 32000
 
   echo -n "Starting mongod: "
-  $NUMACTL /sbin/start_daemon -u "$MONGO_USER" -p "$PIDFILEPATH" $mongod $OPTIONS >/dev/null 2>&1
+  $mongod $OPTIONS >/dev/null 2>&1
 
   RETVAL=$?
-  [ $RETVAL -eq 0 ] && touch {{ezpaarse-mongo-path}}/var/lock/subsys/mongod
+  [ $RETVAL -eq 0 ] && touch ${EZPAARSE_MONGO_PATH}/var/lock/subsys/mongod
   return $RETVAL
 }
 
 stop()
 {
   echo -n "Stopping mongod: "
-  mongo_killproc "$PIDFILEPATH" $mongod
-  RETVAL=$?
-  [ $RETVAL -eq 0 ] && rm -f {{ezpaarse-mongo-path}}/var/lock/subsys/mongod
-  return $RETVAL
+ 
+  kill `cat $PIDFILEPATH` 2>&1
+
+  rm -f "${PIDFILEPATH}"
 }
 
 restart () {
@@ -86,65 +77,21 @@ restart () {
 	start
 }
 
-# Send TERM signal to process and wait up to 300 seconds for process to go away.
-# If process is still alive after 300 seconds, send KILL signal.
-# Built-in killproc() (found in /etc/init.d/functions) is on certain versions of Linux
-# where it sleeps for the full $delay seconds if process does not respond fast enough to
-# the initial TERM signal.
-mongo_killproc()
-{
-  local pid_file=$1
-  local procname=$2
-  local -i delay=300
-  local -i duration=10
-  local pid=`pidofproc -p "${pid_file}" ${procname}`
-
-  kill -TERM $pid >/dev/null 2>&1
-  usleep 100000
-  local -i x=0
-  while [ $x -le $delay ] && checkproc -p "${pid_file}" ${procname}; do
-    sleep $duration
-    x=$(( $x + $duration))
-  done
-
-  kill -KILL $pid >/dev/null 2>&1
-  usleep 100000
-
-  rm -f "${pid_file}"
-
-  checkproc -p "${pid_file}" ${procname}
-  local RC=$?
-  RC=$((! $RC))
-  return $RC
-}
-
 RETVAL=0
 
 case "$1" in
   start)
     start
-    rc_status -v
     ;;
   stop)
     stop
-    rc_status -v
     ;;
   restart|reload|force-reload)
     restart
-    rc_status -v
-    ;;
-  condrestart)
-    [ -f {{ezpaarse-mongo-path}}/var/lock/subsys/mongod ] && restart || :
-    rc_status
-    ;;
-  status)
-    echo -n "Checking for mongod:"
-    checkproc -p "$PIDFILEPATH" $mongod
-    rc_status -v
     ;;
   *)
-    echo "Usage: $0 {start|stop|status|restart|reload|force-reload|condrestart}"
+    echo "Usage: $0 {start|stop|restart|reload|force-reload|condrestart}"
     exit 1
 esac
 
-rc_exit
+exit $RETVAL
